#!/usr/bin/env python3
"""
Compile final occupations.json for the frontend treemap.
Input:  data/processed/occupations_scored.json
Output: data/occupations.json  (committed to repo, loaded by frontend)

Also validates all required fields are present.
"""

import json
from pathlib import Path

DATA = Path(__file__).parent.parent / "data"
IN = DATA / "processed" / "occupations_scored.json"
OUT = DATA / "occupations.json"

REQUIRED_FIELDS = [
    "code", "name", "major_group", "major_group_name",
    "employment", "median_wage", "rural_pct", "informal_pct",
    "ai_exposure", "ai_rationale", "automation_risk",
    "formalization_potential", "skill_gap", "growth_outlook",
]

MAJOR_GROUPS = {
    "1": "Managers", "2": "Professionals", "3": "Technicians",
    "4": "Clerical Support", "5": "Service & Sales", "6": "Agriculture",
    "7": "Craft & Trades", "8": "Machine Operators", "9": "Elementary",
}

VALID_GROWTH = {"declining", "stable", "growing", "fast-growing"}


def validate(occ):
    errors = []
    for f in REQUIRED_FIELDS:
        if f not in occ:
            errors.append(f"missing: {f}")
    if occ.get("employment", 0) <= 0:
        errors.append("employment must be > 0")
    if occ.get("growth_outlook") not in VALID_GROWTH:
        errors.append(f"invalid growth_outlook: {occ.get('growth_outlook')}")
    for score_field in ["ai_exposure", "automation_risk", "formalization_potential", "skill_gap"]:
        v = occ.get(score_field)
        if v is not None and not (0 <= v <= 10):
            errors.append(f"{score_field}={v} out of range 0-10")
    return errors


def main():
    if not IN.exists():
        print(f"Scored data not found: {IN}")
        print("Run 4_score.py first.")
        return

    scored = json.loads(IN.read_text())
    print(f"Input: {len(scored)} occupations")

    valid = []
    skipped = 0
    for occ in scored:
        errors = validate(occ)
        if errors:
            print(f"  [SKIP] NCO {occ.get('code')} {occ.get('name')}: {errors}")
            skipped += 1
        else:
            # Keep only fields needed by frontend
            valid.append({
                "code":                   occ["code"],
                "name":                   occ["name"],
                "major_group":            occ["major_group"],
                "major_group_name":       occ["major_group_name"],
                "employment":             int(occ["employment"]),
                "median_wage":            int(occ["median_wage"]),
                "rural_pct":              int(occ["rural_pct"]),
                "informal_pct":           int(occ["informal_pct"]),
                "ai_exposure":            int(occ["ai_exposure"]),
                "ai_rationale":           occ["ai_rationale"],
                "automation_risk":        int(occ["automation_risk"]),
                "formalization_potential": int(occ["formalization_potential"]),
                "skill_gap":              int(occ["skill_gap"]),
                "growth_outlook":         occ["growth_outlook"],
                "ncs_url":                occ.get("ncs_url", "https://ncs.gov.in"),
            })

    valid.sort(key=lambda x: -x["employment"])

    total_workers = sum(o["employment"] for o in valid)

    output = {
        "meta": {
            "title": "IndianJobsMap",
            "total_workers": total_workers,
            "source": "PLFS 2022-23 (MoSPI), NCS Portal, NCO-2015",
            "scored_by": "Claude Haiku (claude-haiku-4-5-20251001)",
        },
        "major_groups": MAJOR_GROUPS,
        "occupations": valid,
    }

    json_str = json.dumps(output, indent=2, ensure_ascii=False)
    OUT.write_text(json_str)

    # Also write occupations.js for file:// compatibility
    js_out = DATA / "occupations.js"
    js_out.write_text(
        "/* Auto-generated by pipeline/5_compile.py — do not edit manually */\n"
        f"window.JOBS_DATA = {json_str};\n"
    )
    print(f"Also saved → {js_out}")

    print(f"Output: {len(valid)} occupations ({skipped} skipped)")
    print(f"Total workers: {total_workers:,}")
    print(f"File size: {OUT.stat().st_size / 1024:.1f} KB")
    print(f"Saved → {OUT}")

    # Summary by major group
    print("\nBy major group:")
    from collections import defaultdict
    groups = defaultdict(lambda: {"count": 0, "workers": 0})
    for o in valid:
        g = groups[o["major_group_name"]]
        g["count"] += 1
        g["workers"] += o["employment"]
    for name, g in sorted(groups.items()):
        print(f"  {name:25s} {g['count']:3d} occs  {g['workers']/1e7:.1f}Cr workers")


if __name__ == "__main__":
    main()
