#!/usr/bin/env python3
"""
Compile the final occupations.json/.js for the treemap from:
  - data/processed/plfs2025_by_nco.json   (run 6_parse_plfs2025.py first)
  - pipeline/scores_2025.py                (AI / India scores, all NCO codes)

Output: data/occupations.json + data/occupations.js

This replaces the old 40-occupation hand-built dataset with the full set of
NCO-2015 groups observed in PLFS CY2025 (about 118 occupations covering the
whole 61.6 crore workforce).
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from scores_2025 import S, NAME_FIX

ROOT = Path(__file__).parent.parent
STATS = ROOT / "data" / "processed" / "plfs2025_by_nco.json"
OUT_JSON = ROOT / "data" / "occupations.json"
OUT_JS = ROOT / "data" / "occupations.js"

MAJOR_GROUPS = {
    "1": "Managers", "2": "Professionals", "3": "Technicians",
    "4": "Clerical Support", "5": "Service & Sales", "6": "Agriculture",
    "7": "Craft & Trades", "8": "Machine Operators", "9": "Elementary",
}


def main():
    stats = json.loads(STATS.read_text(encoding="utf-8"))
    occupations = []
    missing = []

    for r in stats:
        code = r["code"]
        sc = S.get(code)
        if not sc:
            missing.append(code)
            continue
        ai, autom, formal, gig, growth, rationale, india = sc
        occupations.append({
            "code": code,
            "name": NAME_FIX.get(code, r["name"]),
            "major_group": r["major_group"],
            "major_group_name": r["major_group_name"],
            "employment": r["employment"],
            "median_wage": r["median_wage"],
            "rural_pct": r["rural_pct"],
            "informal_pct": r["informal_pct"],
            "data_vintage": "PLFS 2025 (Jan-Dec)",
            "india_note": india,
            "ai_exposure": ai,
            "ai_rationale": rationale,
            "automation_risk": autom,
            "formalization_potential": formal,
            "gig_potential": gig,
            "growth_outlook": growth,
        })

    occupations.sort(key=lambda x: -x["employment"])
    total = sum(o["employment"] for o in occupations)

    out = {
        "meta": {
            "title": "Indian Jobs Map",
            "tagline": "India's 61.6 crore workforce, occupation by occupation",
            "total_workers": 616000000,
            "mapped_workers": total,
            "occupation_count": len(occupations),
            "data_vintage": "PLFS Calendar Year 2025 unit-level microdata (first visit)",
            "wage_vintage": "PLFS 2025, median annual earnings (regular monthly x12; self-employed monthly x12; casual weekly x52)",
            "source_primary": "Periodic Labour Force Survey, Calendar Year 2025 (Jan-Dec 2025), unit-level microdata CPERV1, NSO/MoSPI",
            "source_secondary": "PLFS Annual Report 2025 press note; PLFS Monthly Bulletin April 2026; NITI Aayog Gig Report 2022; NASSCOM 2024",
            "method": "Person records aggregated with survey weights (MULT/100), usual status (ps+ss) workers aged 15+, classified to NCO-2015 3-digit codes. Survey total of 51.9 crore workers post-stratified to the official 61.6 crore (MoSPI applies WPR to MoHFW projected population).",
            "scored_by": "Karpathy-style anchored 0-10 AI exposure scale, India-context labour-economist scoring (see pipeline/scores_2025.py)",
            "caveat": "AI Exposure does not predict job loss. It estimates how much current AI (language models, vision, code) can reshape daily work, not whether demand for the occupation will fall. PLFS 2025 used a revamped survey design and is not strictly comparable with rounds up to 2023-24.",
        },
        "major_groups": MAJOR_GROUPS,
        "occupations": occupations,
    }

    js = json.dumps(out, indent=2, ensure_ascii=False)
    OUT_JSON.write_text(js, encoding="utf-8")
    OUT_JS.write_text("/* Auto-generated by 5b_compile_2025.py - do not edit manually */\n"
                      "window.JOBS_DATA = " + js + ";\n", encoding="utf-8")

    print(f"Compiled {len(occupations)} occupations -> {OUT_JSON.name}, {OUT_JS.name}")
    print(f"Mapped workers: {total/1e7:.1f} crore (official total 61.6 crore)")
    if missing:
        print(f"WARNING: {len(missing)} NCO codes had no score and were dropped: {missing}")

    # group summary
    from collections import defaultdict
    g = defaultdict(lambda: [0, 0])
    for o in occupations:
        g[o["major_group_name"]][0] += 1
        g[o["major_group_name"]][1] += o["employment"]
    print("\nBy major group:")
    for name, (c, w) in sorted(g.items(), key=lambda x: -x[1][1]):
        print(f"  {name:18s} {c:3d} occs  {w/1e7:6.1f} Cr  {100*w/total:4.1f}%")


if __name__ == "__main__":
    main()
